/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Addstudent;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhay Goyal
 */
public class Selectsubs extends javax.swing.JFrame {

    /**
     * Creates new form Selectsubs
     */
    
    String regno,status;
    public Selectsubs() {
        initComponents();
    }
    
    public Selectsubs(String regno, String status)
    {
        initComponents();
        this.regno=regno;
        this.status=status;
    }
    
    int val1;
    public void getoptions(int val)
    {
        val1=val;
    }
    
    public int sendoptions()
    {
        return val1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Subject 1:-");

        jLabel2.setText("Subject 2:-");

        jLabel3.setText("Subject 3:-");

        jLabel4.setText("Subject 4:-");

        jLabel5.setText("Subject 5:-");

        jLabel6.setText("Subject 6:-");

        jLabel7.setText("Subject 7:-");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        jButton1.setText("Select Subjects");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Subject 8:-");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory of Computation", "Computer Networks", "Big data Analytics", "Python Programming", "Mobile App development", "Machine Learning ", "IOT", "Maths", "Database Management Systems", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    /*public void detain(String regno)
    {
         try
        {
            Class.forName("java.sql.Driver");
            //ArrayList<String> opt=new ArrayList<>();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/backcheck","root","abhay");
            Statement stmt=(Statement) con.createStatement();
            String sql="Select subject1, subject2 from actual where regno='"+regno+"';";
            String subject1="",subject2="";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                subject1=rs.getString(1);
                subject2=rs.getString(2);
            }
            
            Finalshow f=new Finalshow();
            f.setVisible(true);
            this.setVisible(false);
            //f.getshow(subject1, subject2, 1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }*/
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int flag=0;
        String s0="",s1="",s2="",s3="",s4="",s5="",s6="",s7="";
        
            
         s0=(String)jComboBox1.getSelectedItem();
         s1=(String)jComboBox2.getSelectedItem();
         s2=(String)jComboBox3.getSelectedItem();
         s3=(String)jComboBox4.getSelectedItem();
         s4=(String)jComboBox5.getSelectedItem();
         s5=(String)jComboBox6.getSelectedItem();
         s6=(String)jComboBox7.getSelectedItem();
         s7=(String)jComboBox8.getSelectedItem();
        String checksame[]={s0,s1,s2,s3,s4,s5,s6,s7};
        String allsubs[]={s0,s1,s2,s3,s4,s5,s6,s7};
        //int flag=0;
        for(int i=0;i<7;i++)
        {
            for(int j=i;j<7;j++)
            {
                if(checksame[j].equals(checksame[j+1]))
                {
                    System.out.println(checksame[i]+" "+checksame[j]);
                    flag=1;
                    //JOptionPane.showMessageDialog(null, "Please enter different subjects");
                    break;
                }
            }
        }
        

        //flag=0
        if(flag==1)
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s0.isEmpty() || s1.isEmpty() || s2.isEmpty() || s3.isEmpty() || s4.isEmpty() || s5.isEmpty() || s6.isEmpty() || s7.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter all the details");
        }

        /*
        if(s1.equals(s2) || s1.equals(s3) || s1.equals(s4) || s1.equals(s5) || s1.equals(s6) || s1.equals(s7) || s8.equals(s1))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s2.equals(s1) || s2.equals(s3) || s2.equals(s4) || s2.equals(s5) || s2.equals(s6) || s2.equals(s7) || s2.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s3.equals(s2) || s3.equals(s1) || s3.equals(s4) || s3.equals(s5) || s3.equals(s6) || s3.equals(s7) || s3.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s4.equals(s2) || s4.equals(s3) || s4.equals(s1) || s4.equals(s5) || s4.equals(s6) || s4.equals(s7) || s4.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s5.equals(s2) || s5.equals(s3) || s5.equals(s4) || s5.equals(s1) || s5.equals(s6) || s5.equals(s7) || s5.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s6.equals(s2) || s6.equals(s3) || s6.equals(s4) || s6.equals(s1) || s6.equals(s1) || s6.equals(s7) || s6.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s7.equals(s2) || s7.equals(s3) || s7.equals(s4) || s7.equals(s1) || s7.equals(s6) || s7.equals(s1) || s7.equals(s8))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }

        if(s8.equals(s2) || s8.equals(s3) || s8.equals(s4) || s8.equals(s1) || s8.equals(s6) || s8.equals(s7) || s8.equals(s1))
        {
            JOptionPane.showMessageDialog(null, "Please enter different subjects");
        }
        */
        String a1[]={"Computer Networks", "Theory of Computation" , "Maths", "Database Management Systems"};
        ArrayList<String> all=new ArrayList<String>();
        flag=0;
        for(int i=0;i<8;i++)
        {
            flag=0;
            for(int j=0;j<4;j++)
            {
                if(allsubs[i].equals(a1[j]))
                {
                    //flag++;
                    flag=2;
                    break;
                }
                else
                {
                    flag=1;

                }
            }
            if(flag==1)
            {
                all.add(allsubs[i]);
            }

        }

        System.out.print(all);
        //return;

        try
        {
            Class.forName("java.sql.Driver");
            ArrayList<String> opt=new ArrayList<>();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/backcheck","root","abhay");
            Statement stmt=(Statement) con.createStatement();int val=0;
            int l=all.size();String subject;
            System.out.println(all);
            for(int i=0;i<l;i++)
            {
                subject=all.get(i);
                String s="Select counttaken from optionalsubjects where course='"+subject+"';";
                System.out.println(s);
                ResultSet rs=stmt.executeQuery(s);
                while(rs.next())
                {
                    val=rs.getInt(1);
                    System.out.println(val);
                }
                if(val>=60)
                {
                    //i++;
                    continue;
                }
                else
                opt.add(subject);
            }
            System.out.print("Done here2 ");
            System.out.println(opt);
            System.out.print("Done here1 ");
            String s1opt=opt.get(0);
            String s2opt=opt.get(1);
            System.out.print("Done here "+s1opt+s2opt);
            
            String sql1="Select count(id) from login;";
            int value=0;
            ResultSet rs1=stmt.executeQuery(sql1);
            while(rs1.next())
            {
                value=rs1.getInt(1);
            }
            
            
            //int valuable=13456788;
            String sql="Insert into login values("+(value+1)+",'','"+s1opt+"','"+s2opt+"');";
            
            System.out.println(sql);
            
            System.out.print(stmt.executeUpdate(sql));
            
            //Selectsubs s=new Selectsubs();
            //s.getoptions(value+1);
            System.out.print("Don here 4566");
            
            //System.out.print("Done here "+s1opt+s2opt);
            Finalshownotdetain f=new Finalshownotdetain(value+1);
           // new Finalshow(s1opt,s2opt);
            f.setVisible(true);
            this.setVisible(false);
            //Finalshow Finalshow=new Finalshow(s1opt,s2opt);
            //Finalshow.setVisible(true);
        }
        catch(Exception e)
        {   
                JOptionPane.showMessageDialog(this,e.getMessage());

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selectsubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selectsubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selectsubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selectsubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selectsubs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
